services:
  db:
    image: postgres
    container_name: notemancer-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:
      - 5433:5432
    volumes:
      - db:/data/postgres

volumes:
  db:
